name: Build and Deploy to VPS

on:
  push:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/cesairenguefack/sohblitz-backend
  IMAGE_FRONTEND: ghcr.io/cesairenguefack/sohblitz-frontend
  VPS_IP: 51.65.75.254
  VPS_USER: sublime

jobs:

  # =========================
  # 1. BUILD & PUSH IMAGES
  # =========================
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build & Push Backend
        run: |
          docker build -t $IMAGE_BACKEND:${{ github.sha }} ./sohblitz-backend
          docker push $IMAGE_BACKEND:${{ github.sha }}

          docker tag $IMAGE_BACKEND:${{ github.sha }} $IMAGE_BACKEND:latest
          docker push $IMAGE_BACKEND:latest

      - name: Build & Push Frontend
        run: |
          docker build -t $IMAGE_FRONTEND:${{ github.sha }} ./sohblitz-frontend
          docker push $IMAGE_FRONTEND:${{ github.sha }}

          docker tag $IMAGE_FRONTEND:${{ github.sha }} $IMAGE_FRONTEND:latest
          docker push $IMAGE_FRONTEND:latest

  # =========================
  # 2. DEPLOY TO VPS
  # =========================
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts

      - name: Deploy on VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
            set -e
      
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u CesaireNguefack --password-stdin
      
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
      
            docker image prune -f
          EOF
